version: '3.8'

services:
  open-webui:
    image: berkay:1.1.3
    container_name: open-webui
    restart: always
    environment:
      - CORS_ALLOW_ORIGIN=http://localhost:5173
      - FRONTEND_BUILD_DIR=/app/frontend
    expose:
      - 8080

    networks:
      - openwebui-net

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - open-webui
    volumes:
      - /home/hasret/Documents/Time-Reactor/open-webui/nginx.conf:/etc/nginx/conf.d/default.conf:ro

    networks:
      - openwebui-net
   
networks:
  openwebui-net:
    driver: bridge
